-- AI character tagging fields and background job tables.
alter table public.products
  add column if not exists characters jsonb not null default '[]'::jsonb,
  add column if not exists character_suggestions jsonb,
  add column if not exists character_review_status text not null default 'untagged',
  add column if not exists character_tagged_at timestamptz;

create table if not exists public.character_tagging_jobs (
  id bigint generated by default as identity primary key,
  status text not null default 'running',
  total_products integer not null default 0,
  processed_count integer not null default 0,
  auto_tagged_count integer not null default 0,
  needs_review_count integer not null default 0,
  failed_count integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.character_tagging_job_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.character_tagging_jobs(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  status text not null default 'pending',
  attempts integer not null default 0,
  result jsonb,
  error text,
  claimed_at timestamptz,
  processed_at timestamptz,
  unique(job_id, product_id)
);

create index if not exists character_tagging_job_items_claim_idx
  on public.character_tagging_job_items(job_id, status, id);

create or replace function public.claim_character_tagging_items(p_job_id bigint, p_limit integer)
returns setof public.character_tagging_job_items
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with claimed as (
    select id
    from public.character_tagging_job_items
    where job_id = p_job_id and status = 'pending'
    order by id
    for update skip locked
    limit p_limit
  )
  update public.character_tagging_job_items item
  set status = 'processing', claimed_at = now()
  from claimed
  where item.id = claimed.id
  returning item.*;
end;
$$;

create or replace function public.increment_character_job_progress(
  p_job_id bigint,
  p_processed integer,
  p_auto_tagged integer,
  p_needs_review integer,
  p_failed integer
)
returns setof public.character_tagging_jobs
language sql
security definer
set search_path = public
as $$
  update public.character_tagging_jobs
  set processed_count = processed_count + p_processed,
      auto_tagged_count = auto_tagged_count + p_auto_tagged,
      needs_review_count = needs_review_count + p_needs_review,
      failed_count = failed_count + p_failed
  where id = p_job_id
  returning *;
$$;